/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainLayoutRouteImport } from './routes/_mainLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainLayoutJournalRouteImport } from './routes/_mainLayout/journal'
import { Route as MainLayoutSettingsIndexRouteImport } from './routes/_mainLayout/settings.index'
import { Route as MainLayoutAdminIndexRouteImport } from './routes/_mainLayout/admin/index'
import { Route as MainLayoutSettingsSectionRouteImport } from './routes/_mainLayout/settings.$section'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutJournalRoute = MainLayoutJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutSettingsIndexRoute = MainLayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAdminIndexRoute = MainLayoutAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutSettingsSectionRoute =
  MainLayoutSettingsSectionRouteImport.update({
    id: '/settings/$section',
    path: '/settings/$section',
    getParentRoute: () => MainLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journal': typeof MainLayoutJournalRoute
  '/settings/$section': typeof MainLayoutSettingsSectionRoute
  '/admin': typeof MainLayoutAdminIndexRoute
  '/settings': typeof MainLayoutSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journal': typeof MainLayoutJournalRoute
  '/settings/$section': typeof MainLayoutSettingsSectionRoute
  '/admin': typeof MainLayoutAdminIndexRoute
  '/settings': typeof MainLayoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/_mainLayout/journal': typeof MainLayoutJournalRoute
  '/_mainLayout/settings/$section': typeof MainLayoutSettingsSectionRoute
  '/_mainLayout/admin/': typeof MainLayoutAdminIndexRoute
  '/_mainLayout/settings/': typeof MainLayoutSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/journal' | '/settings/$section' | '/admin' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/journal' | '/settings/$section' | '/admin' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_mainLayout'
    | '/_mainLayout/journal'
    | '/_mainLayout/settings/$section'
    | '/_mainLayout/admin/'
    | '/_mainLayout/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/journal': {
      id: '/_mainLayout/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof MainLayoutJournalRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/settings/': {
      id: '/_mainLayout/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainLayoutSettingsIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/admin/': {
      id: '/_mainLayout/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof MainLayoutAdminIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/settings/$section': {
      id: '/_mainLayout/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof MainLayoutSettingsSectionRouteImport
      parentRoute: typeof MainLayoutRoute
    }
  }
}

interface MainLayoutRouteChildren {
  MainLayoutJournalRoute: typeof MainLayoutJournalRoute
  MainLayoutSettingsSectionRoute: typeof MainLayoutSettingsSectionRoute
  MainLayoutAdminIndexRoute: typeof MainLayoutAdminIndexRoute
  MainLayoutSettingsIndexRoute: typeof MainLayoutSettingsIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutJournalRoute: MainLayoutJournalRoute,
  MainLayoutSettingsSectionRoute: MainLayoutSettingsSectionRoute,
  MainLayoutAdminIndexRoute: MainLayoutAdminIndexRoute,
  MainLayoutSettingsIndexRoute: MainLayoutSettingsIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainLayoutRoute: MainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
