/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeLayoutRouteImport } from './routes/_welcomeLayout'
import { Route as MainLayoutRouteImport } from './routes/_mainLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainLayoutCategoriesRouteImport } from './routes/_mainLayout/categories'
import { Route as MainLayoutAccountsRouteImport } from './routes/_mainLayout/accounts'
import { Route as MainLayoutSettingsIndexRouteImport } from './routes/_mainLayout/settings.index'
import { Route as MainLayoutJournalIndexRouteImport } from './routes/_mainLayout/journal.index'
import { Route as MainLayoutSettingsSectionRouteImport } from './routes/_mainLayout/settings.$section'
import { Route as MainLayoutJournalViewSplatRouteImport } from './routes/_mainLayout/journal.$view.$'

const WelcomeLayoutRoute = WelcomeLayoutRouteImport.update({
  id: '/_welcomeLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutCategoriesRoute = MainLayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAccountsRoute = MainLayoutAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutSettingsIndexRoute = MainLayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutJournalIndexRoute = MainLayoutJournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutSettingsSectionRoute =
  MainLayoutSettingsSectionRouteImport.update({
    id: '/settings/$section',
    path: '/settings/$section',
    getParentRoute: () => MainLayoutRoute,
  } as any)
const MainLayoutJournalViewSplatRoute =
  MainLayoutJournalViewSplatRouteImport.update({
    id: '/journal/$view/$',
    path: '/journal/$view/$',
    getParentRoute: () => MainLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof MainLayoutAccountsRoute
  '/categories': typeof MainLayoutCategoriesRoute
  '/settings/$section': typeof MainLayoutSettingsSectionRoute
  '/journal': typeof MainLayoutJournalIndexRoute
  '/settings': typeof MainLayoutSettingsIndexRoute
  '/journal/$view/$': typeof MainLayoutJournalViewSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof MainLayoutAccountsRoute
  '/categories': typeof MainLayoutCategoriesRoute
  '/settings/$section': typeof MainLayoutSettingsSectionRoute
  '/journal': typeof MainLayoutJournalIndexRoute
  '/settings': typeof MainLayoutSettingsIndexRoute
  '/journal/$view/$': typeof MainLayoutJournalViewSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_mainLayout': typeof MainLayoutRouteWithChildren
  '/_welcomeLayout': typeof WelcomeLayoutRoute
  '/_mainLayout/accounts': typeof MainLayoutAccountsRoute
  '/_mainLayout/categories': typeof MainLayoutCategoriesRoute
  '/_mainLayout/settings/$section': typeof MainLayoutSettingsSectionRoute
  '/_mainLayout/journal/': typeof MainLayoutJournalIndexRoute
  '/_mainLayout/settings/': typeof MainLayoutSettingsIndexRoute
  '/_mainLayout/journal/$view/$': typeof MainLayoutJournalViewSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/categories'
    | '/settings/$section'
    | '/journal'
    | '/settings'
    | '/journal/$view/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/categories'
    | '/settings/$section'
    | '/journal'
    | '/settings'
    | '/journal/$view/$'
  id:
    | '__root__'
    | '/'
    | '/_mainLayout'
    | '/_welcomeLayout'
    | '/_mainLayout/accounts'
    | '/_mainLayout/categories'
    | '/_mainLayout/settings/$section'
    | '/_mainLayout/journal/'
    | '/_mainLayout/settings/'
    | '/_mainLayout/journal/$view/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  WelcomeLayoutRoute: typeof WelcomeLayoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_welcomeLayout': {
      id: '/_welcomeLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WelcomeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainLayout/categories': {
      id: '/_mainLayout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof MainLayoutCategoriesRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/accounts': {
      id: '/_mainLayout/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof MainLayoutAccountsRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/settings/': {
      id: '/_mainLayout/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainLayoutSettingsIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/journal/': {
      id: '/_mainLayout/journal/'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof MainLayoutJournalIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/settings/$section': {
      id: '/_mainLayout/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof MainLayoutSettingsSectionRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_mainLayout/journal/$view/$': {
      id: '/_mainLayout/journal/$view/$'
      path: '/journal/$view/$'
      fullPath: '/journal/$view/$'
      preLoaderRoute: typeof MainLayoutJournalViewSplatRouteImport
      parentRoute: typeof MainLayoutRoute
    }
  }
}

interface MainLayoutRouteChildren {
  MainLayoutAccountsRoute: typeof MainLayoutAccountsRoute
  MainLayoutCategoriesRoute: typeof MainLayoutCategoriesRoute
  MainLayoutSettingsSectionRoute: typeof MainLayoutSettingsSectionRoute
  MainLayoutJournalIndexRoute: typeof MainLayoutJournalIndexRoute
  MainLayoutSettingsIndexRoute: typeof MainLayoutSettingsIndexRoute
  MainLayoutJournalViewSplatRoute: typeof MainLayoutJournalViewSplatRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutAccountsRoute: MainLayoutAccountsRoute,
  MainLayoutCategoriesRoute: MainLayoutCategoriesRoute,
  MainLayoutSettingsSectionRoute: MainLayoutSettingsSectionRoute,
  MainLayoutJournalIndexRoute: MainLayoutJournalIndexRoute,
  MainLayoutSettingsIndexRoute: MainLayoutSettingsIndexRoute,
  MainLayoutJournalViewSplatRoute: MainLayoutJournalViewSplatRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainLayoutRoute: MainLayoutRouteWithChildren,
  WelcomeLayoutRoute: WelcomeLayoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
